### ISSUE TITLE
Plugin not recognizing channel enviroment variable.

### ISSUE THREAD

**Issue by paulosergiolima** [hardliner66/neovim-twitch-chat#2]
I have setup all the needed variables in the init.lua file, and they are working, however I still get this error: 
``Error detected while processing function twitchChat#sendLine[2]..twitchChat#sendMessage:                                    
line 1:
E475: Invalid argument: Channel doesn't exist ``

**Comment by hardliner66** [comment]
Did you set the environment variables as well?

**Comment by paulosergiolima** [comment]
Yes, but I did it after the plugin started, setting the environment variables before the plugin starts fixes it. Thanks!
